### ISSUE TITLE
Error when starting bots

### ISSUE THREAD

**Issue by muelleel** [redstorm45/mc-stresstest#1]
Hey,
I want to stresstest an Offline-Papermc server on my local network.

I'm getting the following message(s) when starting:

```
sudo docker-compose up
Starting mc-stresstest_client_1 ... done
Attaching to mc-stresstest_client_1
client_1  | This is a test!
client_1  | Trying to launch 1 bots
client_1  | Launch bot number 1
client_1  | TypeError: Cannot read property 'version' of null
client_1  |     at Client.next (/node_modules/mineflayer/lib/loader.js:108:67)
client_1  |     at Object.onceWrapper (events.js:519:28)
client_1  |     at Client.emit (events.js:412:35)
client_1  |     at /node_modules/minecraft-protocol/src/client/autoVersion.js:53:12
client_1  |     at /node_modules/minecraft-protocol/src/ping.js:13:7
client_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

after that the program terminates after an while...

Maybe the mineflayer does not recognize the new Minecraft versions? (the Server is currently on latest 1.19)

configuration:
```
version: "3"
    
services:
  client:
    build: .
    restart: always
    network_mode: "host"
    environment:
      - PLAYER_COUNT=1
      - SERVER_IP=192.168.x.x
      - SERVER_PORT=25565
    volumes:
      - ./scripts:/app/scripts
```
what does the network_mode option? Seems to not be documented...

Running on Linux based on Debian/Ubuntu 
Any ideas? Thanks :)

Edit: needless to say, I can connect normally with an minecraft client to the given Ip.
